import { AuditResult } from "@/types/results";

export const demoReport: AuditResult = {
  totalCurrentMonthlySpend: 3165,
  totalOptimizedMonthlySpend: 1340,
  totalMonthlySavings: 1825,
  totalAnnualSavings: 21900,
  percentageSaved: 57.66,
  optimizationScore: {
    label: "Poor",
    tone: "poor",
    description: "Significant waste of $1,825/mo detected. Highly redundant chatbot and developer seat allocations.",
  },
  highestSavingTool: "ChatGPT",
  highestSavingAmount: 1075,
  recommendations: [
    {
      tool: "ChatGPT",
      currentPlan: "Enterprise (20 seats @ $60)",
      recommendedPlan: "Consolidate (Prune to 5 Team seats @ $25, move others to Claude)",
      monthlySpend: 1200,
      monthlySavings: 1075,
      annualSavings: 12900,
      reason: "High licensing overlap with Claude Team. General chatbot utilities are already covered for the whole workspace. Consolidate to 5 Team seats for OpenAI API developers, and move the rest to Claude.",
      severity: "High",
    },
    {
      tool: "Cursor",
      currentPlan: "Business (15 seats @ $40)",
      recommendedPlan: "Pro (15 seats @ $20)",
      monthlySpend: 600,
      monthlySavings: 300,
      annualSavings: 3600,
      reason: "Centralized SAML controls are currently unused by the development team. Downgrading developer accounts to the Pro tier retains identical model access while saving 50%.",
      severity: "High",
    },
    {
      tool: "GitHub Copilot",
      currentPlan: "Enterprise (15 seats @ $39)",
      recommendedPlan: "Business (15 seats @ $19)",
      monthlySpend: 585,
      monthlySavings: 300,
      annualSavings: 3600,
      reason: "Custom enterprise search indexers and internal docs query integrations are disabled. Stepping down to the Business tier preserves all autocomplete capabilities.",
      severity: "High",
    },
    {
      tool: "Claude",
      currentPlan: "Team (20 seats @ $25)",
      recommendedPlan: "Keep Plan (20 seats @ $25)",
      monthlySpend: 500,
      monthlySavings: 0,
      annualSavings: 0,
      reason: "Claude Team plan is highly active and optimized for writing, brainstorms, and coding artifacts across the entire organization.",
      severity: "Low",
    },
    {
      tool: "Midjourney",
      currentPlan: "Pro (3 seats @ $60)",
      recommendedPlan: "Standard (3 seats @ $30)",
      monthlySpend: 180,
      monthlySavings: 90,
      annualSavings: 1080,
      reason: "Fast rendering hours are consistently underutilized by design seats. Stepping down to the Standard tier provides unlimited relaxed render hours.",
      severity: "Medium",
    },
    {
      tool: "Perplexity",
      currentPlan: "Pro (5 seats @ $20)",
      recommendedPlan: "Prune (Reclaim 3 inactive seats)",
      monthlySpend: 100,
      monthlySavings: 60,
      annualSavings: 720,
      reason: "Three out of five search researcher seats show zero active searches in the past 30 days. Trimming down to 2 active seats eliminates waste.",
      severity: "Medium",
    },
  ],
};