export const GOVERNANCE_THRESHOLDS = {
  DORMANT_DAYS: 30,
  LOW_UTILIZATION_PERCENT: 20,
  ADOPTION_WARNING_PERCENT: 35,
  UNKNOWN_TOOL_THRESHOLD: 5,
  SYNC_STALENESS_HOURS: 24,
  OVERLAP_THRESHOLD: 1
};
